wandb:
  project_name: "mdp-learning"

training:
  mode: 1
  num_layers: 8
  num_heads: 4
  batch_size: 128
  seq_len: 52
  train_ratio: 0.8
  val_ratio: 0.1
  data_path: "info.txt"
  epochs: 50
  lr: 0.0001
  weight_decay: 0.01
  save_directory: "./"
  embedding_size: 128
  seed: 1243
